sudo: false

notifications:
  email: false

language: python

matrix:
  include:
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36

cache:
  - pip

install:
  - pip install -U pip wheel
  - pip install -r test_requirements.txt

script:
  - tox
